name: "ci"
on: [push]
jobs:
  RunCI:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          cache: "npm"
      - run: npm install
      - run: npm test
